---

port: 4430
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "GoodAir"
keywords:    "pollution, air, deep learning, tensorflow, artificial intelligence"
description: "Project to fight against pollution using Deep Learning with TensorFlow"
source_link: "https://agussomacal.github.io/GoodAir"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
pollutionicon: "img/pollutionicon_kbs_icon"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  white:      '#f8f8f8'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'
  gray:       '#b2b2b2'
  greeny:     '#9acc76'
  lightgray:  '#daddd8'
  testcolor:  '#fab125'
  whowecolor: '#91bdc6'

kramdown:
  auto_ids:  false
